### ISSUE TITLE
Does not link against installed libraries

### ISSUE THREAD

**Issue by Broever101** [saad039/cusp#2]
I specified linkage against boost and pthread libraries in cusp menu but it didn't link against them. Is it a missing feature?

**Comment by saad039** [comment]
Initially, I wanted the user to explicitly edit the premake5.lua files to specify linkage against libraries present in the compiler's search path like "/usr/include" and "/usr/libs" because that makes dependencies platform dependent. From now on, I will be allowing users to specify linkages to dependencies like _pthread_ and _tbb_  but it will be up to them to modify the premake5.lua files to ensure their builds are cross-platform(if they prefer to).

**Comment by saad039** [comment]
I have added the support in this commit.
https://github.com/saad039/cusp/commit/582cdcc8a6536265668794373a14bdbbcd986e80
